travis:
  secure:
    BINSTAR_TOKEN: nmqkBprY7By0mKVs6xIwVJQZJFh5myOt43fo0uOewWOTaAZBfOCpReTSG67ZBZokyTmUC1MLP4PUXUt2cfyKmDiu5xTmIDRwPoznxYz3jr0BzR6h6Xr72izq2bR1qWSVQ5RDsQ+kZGYyHzrQegpRnqpkHBNZOSRTgEJL+75RklFKKF/w7QdRuW/vN5RPwMou4vjC8O59G+2rIEpJGs/mZ5ARnmt/0VQq8FDMFoevpfjH104Z2991ip5EV65jML691U70v96nR4b7udIrB1mIeMhi2fcaFLh0EL/NWllsWw68w0tsdWr64fYSnfsNL4MLzeMPT/ZyFC9lOcZufGphh7OxMz/gnunUPdImjYtd4WdOSrIjDAMYDhJB9+kYitVmMzu6uxoZFLn9+XbC7H/C5WxkbAgTo6czdtJxela3AtGdLpprGCS25F5PivPoutdHOtYdQ+z1mxFARuEpqHjZ05kma0K5DJs2a60tYo2aKc8HIfNgbkyoqDkrKnZp9Ki+Iky6SisF3nZIuzVbFDm3X/yawwbHdaLB1h24qTZYAl8jqJPg4f5wZdIZIFHqxatI69B6733OiqTrBN/aUPKPjRgd6iE9R3ni2S4NWqC5VZEzErC9jxQxs0vP37zQ5bUjAP6JsBRabKivGCJYnFvTJ35pIbswxsxsGAsIYjk0sHk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
